[workspace]
members = ["sdplay-lib", "sdplay", "sdplay-serve"]

[patch.crates-io]
sdplay-lib = { path = "./sdplay-lib" }


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-web]
inherits = "release"
opt-level = "s"
