name: Release binary artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-latest
            ext: ""
          - target: x86_64-pc-windows-msvc
            image: windows-latest
            ext: ".exe"
          - target: x86_64-apple-darwin
            image: macos-latest
            ext: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Package Binaries
        uses: vimtor/action-zip@v1
        with:
          files: target/release/sdp-player${{ matrix.ext }}
          dest: sdp-player-${{ matrix.target }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sdp-player-${{ matrix.target }}.zip

      # TODO publish to crates.io
